### ISSUE TITLE
[meta] 1.0 Release: Small fixes

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#89]
- [x] GraphQL Bin landing page: invalid URL
- [x] History popup: Settings + sharing button shouldn't be visible
- [x] Dark theme should be default
- [x] Sharing copy button is missing
- [x] Sharing options don't work
- [x] Type descriptions missing in auto-completion
- [x] Cursor should be in second line by default so user can start typing right away
- [x] New tabs should be empty be default
- [x] Hover states for settings/history button
- [x] indentation of type details wrong
- [x] unnecessary docs scrollbar
- [x] docs white hover error

**Comment by schickling** [comment]
Spacing wrong. See screenshot in #76 for reference:

![image](https://user-images.githubusercontent.com/1567498/30869582-cd3e8ff6-a2e1-11e7-8c5f-52e0717e5810.png)

**Comment by schickling** [comment]
- [ ] Description font size should be `14px`
- [ ] Spacing wrong for upper description

![image](https://user-images.githubusercontent.com/1567498/30875573-4bf4c52e-a2f4-11e7-9bcc-73776579c947.png)

**Comment by schickling** [comment]
- [ ] Tabs overflow

![image](https://user-images.githubusercontent.com/1567498/30877518-4398d9aa-a2fa-11e7-92af-10196629a0d5.png)

**Comment by schickling** [comment]
- [ ] Scroll right

![image](https://user-images.githubusercontent.com/1567498/30877618-86e43272-a2fa-11e7-96fb-8e8a9bbb12f9.png)

**Comment by schickling** [comment]
- [ ] Replace loading banner with new logo

![image](https://user-images.githubusercontent.com/1567498/30882832-95e4d94c-a30a-11e7-9ea5-c1b8d01b3190.png)
